# Default to trixie, but just set env variable to, for example,
# "debian/bookworm64" to run test against bookworm.
OS_TO_TEST = ENV.fetch("OS_TO_TEST", "debian/trixie64")

Vagrant.configure("2") do |config|
  config.vm.box = OS_TO_TEST

  config.nfs.verify_installed = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "ansible" do |ansible|
    # ansible.verbose = "vvv"
    ansible.extra_vars = {
      "ansible_ssh_user" => "vagrant",
    }
    ansible.raw_arguments = ["--ssh-extra-args", "'-o DSAAuthentication=yes'"]

    ansible.compatibility_mode = "2.0"
    ansible.playbook = "test.yml"
  end
end
