---

- block:

    - name: install podman and acl
      ansible.builtin.apt:
        name:
          - podman
          - acl  # needed by ansible to become an unprivileged user
        update_cache: true
        cache_valid_time: 3600

    - name: ensure vaultwarden group exits
      ansible.builtin.group:
        name: vaultwarden

    - name: ensure vaultwarden user exists and has restrictive settings
      ansible.builtin.user:
        name: vaultwarden
        groups: vaultwarden
        password: "*"
        home: "{{ vaultwarden_dir }}"
        shell: /usr/sbin/nologin

    - name: check if vaultwarden user is lingering
      ansible.builtin.stat:
        path: "/var/lib/systemd/linger/vaultwarden"
      register: vaultwarden_user_lingering

    - name: enable linger for vaultwarden user
      ansible.builtin.command: "loginctl enable-linger vaultwarden"
      when: not vaultwarden_user_lingering.stat.exists

  become: "{{ vaultwarden_become }}"
  become_user: "{{ vaultwarden_become_user }}"

- block:

    - name: check if the old vaultwarden container service unit exists
      ansible.builtin.stat:
        path: ~/.config/systemd/user/container-vaultwarden.service
      register: vaultwarden_old_unit

    - name: migrate from the old generated systemd unit to quadlet
      when: vaultwarden_old_unit.stat.exists
      block:

        - name: old vaultwarden container service must be stopped and disabled
          ansible.builtin.systemd:
            name: container-vaultwarden
            state: stopped
            enabled: false
            scope: user
          failed_when: false

        - name: old vaultwarden container service unit must be absent
          ansible.builtin.file:
            path: ~/.config/systemd/user/container-vaultwarden.service
            state: absent

        - name: old vaultwarden container must be absent
          containers.podman.podman_container:
            name: vaultwarden
            state: absent

    - name: ensure vaultwarden quadlet exists
      containers.podman.podman_container:
        name: vaultwarden
        image: "docker.io/vaultwarden/server:{{ vaultwarden_tag }}"
        ports:
          - "{{ vaultwarden_host_ip }}:{{ vaultwarden_host_port }}:80"
        volume:
          - "vaultwarden-data:/data"
        state: quadlet
        quadlet_filename: vaultwarden
        quadlet_file_mode: "0640"
        quadlet_options:
          - |
            [Install]
            WantedBy=default.target
      register: vaultwarden_quadlet

    - name: vaultwarden container must be started and enabled on systemd
      ansible.builtin.systemd:
        name: vaultwarden
        daemon_reload: true
        state: "{{ 'restarted' if vaultwarden_quadlet.changed else 'started' }}"
        enabled: true
        scope: user

  become: true
  become_user: vaultwarden
