---

- name: Install dependencies and setup user
  become: "{{ yarr_become }}"
  become_user: "{{ yarr_become_user }}"
  block:
    - name: Install podman and dependencies
      ansible.builtin.apt:
        name:
          - podman
          - acl # needed by ansible to become an unprivileged user
          - dbus-user-session # needed by rootless podman to talk to systemd
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure yarr group exits
      ansible.builtin.group:
        name: yarr

    - name: Ensure yarr user exists and has restrictive settings
      ansible.builtin.user:
        name: yarr
        group: yarr
        password: "*"
        home: "{{ yarr_dir }}"
        shell: /usr/sbin/nologin

    - name: Check if yarr user is lingering
      ansible.builtin.stat:
        path: "/var/lib/systemd/linger/yarr"
      register: yarr_user_lingering

    - name: Enable linger for yarr user
      ansible.builtin.command: "loginctl enable-linger yarr"
      when: not yarr_user_lingering.stat.exists
      changed_when: true

- name: Setup yarr quadlet
  become: true
  become_user: yarr
  block:
    - name: Ensure the D-Bus session bus is running for yarr
      ansible.builtin.systemd:
        name: dbus.socket
        state: started
        daemon_reload: true
        scope: user

    - name: Ensure yarr quadlet exists
      containers.podman.podman_container:
        name: yarr
        image: "ghcr.io/eriol/oci-yarr:{{ yarr_tag }}"
        ports:
          - "{{ yarr_host_ip }}:{{ yarr_host_port }}:7070"
        volume:
          - "yarr-data:/data"
        state: quadlet
        quadlet_filename: yarr
        quadlet_file_mode: "0640"
        quadlet_options:
          - |
              [Install]
              WantedBy=default.target
      register: yarr_quadlet

    - name: Yarr container must be started and enabled on systemd
      ansible.builtin.systemd:
        name: yarr
        daemon_reload: true
        state: "{{ 'restarted' if yarr_quadlet.changed else 'started' }}"
        enabled: true
        scope: user
